# fly.toml app configuration file generated for sofexpo-b2b on 2026-08-20T10:57:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sofexpo-b2b'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/sofexpo_b2b.db'

[[mounts]]
  source = 'sofexpo_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
